In [2]:
import torch
import torch.nn as nn

import pprint
pp = pprint.PrettyPrinter()

In [3]:
list_of_lists = [
    [1, 2, 3],
    [4, 5, 6]
]
print(list_of_lists)

[[1, 2, 3], [4, 5, 6]]


In [4]:
# initializing a pytorch tensor
data = torch.tensor([
    [0, 1],
    [2, 3],
    [4, 5]
])
print(data)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [9]:
# two major tensor datatypes are - torch.float32, and torch.int

data = torch.tensor([
    [0, 1],
    [2, 3],
    [4, 5]
], dtype=torch.float32)
print(data)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])


In [17]:
data = torch.tensor([
    [0.11111111, 1],
    [2, 3],
    [4, 5]
])
print(data)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])


In [11]:
# utility functions

zeros = torch.zeros(2, 5)
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [12]:
ones = torch.ones(3, 4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [14]:
rr = torch.arange(1, 10)
rr

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
rr + 2

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
rr * 2

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
# matrix multiplication

a = torch.tensor([
    [0, 1],
    [2, 3],
    [4, 5]
])

b = torch.tensor([
    [0, 1, 2, 3],
    [2, 3, 4, 5]
])


print("the product is: ", a.matmul(b))
print("the other product is: ", a @ b)

the product is:  tensor([[ 2,  3,  4,  5],
        [ 6, 11, 16, 21],
        [10, 19, 28, 37]])
the other product is:  tensor([[ 2,  3,  4,  5],
        [ 6, 11, 16, 21],
        [10, 19, 28, 37]])


In [23]:
v = torch.tensor([1, 2, 3])
v.shape

torch.Size([3])

In [26]:
u = torch.tensor([[1, 2, 3],
            [4, 5, 6]])
u.shape

torch.Size([2, 3])

In [29]:
w = u @ v
print(w)

tensor([14, 32])


In [30]:
w.shape

torch.Size([2])