In [3]:
import torch
import torch.nn as nn

import pprint
pp = pprint.PrettyPrinter()

In [4]:
list_of_lists = [
    [1, 2, 3],
    [4, 5, 6]
]
print(list_of_lists)

[[1, 2, 3], [4, 5, 6]]


In [5]:
# initializing a pytorch tensor
data = torch.tensor([
    [0, 1],
    [2, 3],
    [4, 5]
])
print(data)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [6]:
# two major tensor datatypes are - torch.float32, and torch.int

data = torch.tensor([
    [0, 1],
    [2, 3],
    [4, 5]
], dtype=torch.float32)
print(data)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])


In [7]:
data = torch.tensor([
    [0.11111111, 1],
    [2, 3],
    [4, 5]
])
print(data)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])


In [8]:
# utility functions

zeros = torch.zeros(2, 5)
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [9]:
ones = torch.ones(3, 4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [10]:
rr = torch.arange(1, 10)
rr

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
rr + 2

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
rr * 2

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# matrix multiplication

a = torch.tensor([
    [0, 1],
    [2, 3],
    [4, 5]
])

b = torch.tensor([
    [0, 1, 2, 3],
    [2, 3, 4, 5]
])


print("the product is: ", a.matmul(b))
print("the other product is: ", a @ b)

the product is:  tensor([[ 2,  3,  4,  5],
        [ 6, 11, 16, 21],
        [10, 19, 28, 37]])
the other product is:  tensor([[ 2,  3,  4,  5],
        [ 6, 11, 16, 21],
        [10, 19, 28, 37]])


In [14]:
v = torch.tensor([1, 2, 3])
v.shape

torch.Size([3])

In [15]:
u = torch.tensor([[1, 2, 3],
            [4, 5, 6]])
u.shape

torch.Size([2, 3])

In [16]:
w = u @ v
print(w)

tensor([14, 32])


In [17]:
w.shape

torch.Size([2])

In [18]:
matr_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
matr_2d.shape

torch.Size([2, 3])

In [19]:
matr_3d = torch.tensor([
    [[1, 2, 3, 4], 
    [-2, 5, 6, 9]], 
    
    [[5, 6, 7, 2], 
     [8, 9, 10, 4]],
    
    [[-3, 2, 2, 1], 
     [4, 6, 5, 9]]
])
matr_3d.shape

torch.Size([3, 2, 4])

In [20]:
rr = torch.arange(1, 16)
rr

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
rr.view(5, 3)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])

In [25]:
rr = rr.view(5, 3)
print(rr)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


In [28]:
# numpy to pytorch and vice-versa

import numpy as np

# numpy.ndarray --> torch.Tensor:
arr = np.array([[1, 0, 5]])
data = torch.tensor(arr)

print('this is torch.tensor', arr)


# torch.tensor --> numpy.ndarray:
new_arr = data.numpy()
print('this is numpy array', new_arr)

this is torch.tensor [[1 0 5]]
this is numpy array [[1 0 5]]


In [43]:
data = torch.arange(1, 36, dtype=torch.float32).reshape(5, 7)

# we can perform operations like "sum" over each column
print(data.sum(dim=0))

# or each row
print(data.sum(dim=1))

# we can do other operations as well
print(data.std(dim=1))

tensor([ 75.,  80.,  85.,  90.,  95., 100., 105.])
tensor([ 28.,  77., 126., 175., 224.])
tensor([2.1602, 2.1602, 2.1602, 2.1602, 2.1602])


In [44]:
data.sum()

tensor(630.)

In [47]:
data = torch.tensor([
    [1, 2.2, 9.6],
    [4, -7.2, 6.3]
])

data.shape

torch.Size([2, 3])

In [48]:
data.mean(dim=1)

tensor([4.2667, 1.0333])

In [49]:
data.mean(dim=0)

tensor([ 2.5000, -2.5000,  7.9500])

In [50]:
# Indexing

x = torch.tensor([
    [[1, 2], 
    [3, 4]], 
    
    [[5, 6], 
     [7, 8]],
    
    [[9, 10], 
     [11, 12]]
])
x.shape

torch.Size([3, 2, 2])

In [54]:
x[:, 0]

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])

In [55]:
x[0, :]

tensor([[1, 2],
        [3, 4]])

In [56]:
x[0]

tensor([[1, 2],
        [3, 4]])

In [58]:
# list indexing
x[[0, 2]]

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 9, 10],
         [11, 12]]])

In [61]:
x

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [63]:
x[:, 0, 0]

tensor([1, 5, 9])

In [66]:
x[:, :]

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [67]:
x[:, :, :]

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [68]:
x[0, 0, 0]

tensor(1)

In [69]:
x[0, 0, 0].item()

1

In [70]:
y = torch.tensor([
    [1, 2.2, 9.6],
    [4, -7.2, 6.3]
])

y.shape

torch.Size([2, 3])

In [72]:
# first column
y[:, 0]

tensor([1., 4.])

In [73]:
# first row
y[0, :]

tensor([1.0000, 2.2000, 9.6000])