In [1]:
import torch
import torch.nn as nn

import pprint
pp = pprint.PrettyPrinter()

In [2]:
list_of_lists = [
    [1, 2, 3],
    [4, 5, 6]
]
print(list_of_lists)

[[1, 2, 3], [4, 5, 6]]


In [3]:
# initializing a pytorch tensor
data = torch.tensor([
    [0, 1],
    [2, 3],
    [4, 5]
])
print(data)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [4]:
# two major tensor datatypes are - torch.float32, and torch.int

data = torch.tensor([
    [0, 1],
    [2, 3],
    [4, 5]
], dtype=torch.float32)
print(data)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])


In [5]:
data = torch.tensor([
    [0.11111111, 1],
    [2, 3],
    [4, 5]
])
print(data)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])


In [6]:
# utility functions

zeros = torch.zeros(2, 5)
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [7]:
ones = torch.ones(3, 4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [8]:
rr = torch.arange(1, 10)
rr

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
rr + 2

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
rr * 2

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# matrix multiplication

a = torch.tensor([
    [0, 1],
    [2, 3],
    [4, 5]
])

b = torch.tensor([
    [0, 1, 2, 3],
    [2, 3, 4, 5]
])


print("the product is: ", a.matmul(b))
print("the other product is: ", a @ b)

the product is:  tensor([[ 2,  3,  4,  5],
        [ 6, 11, 16, 21],
        [10, 19, 28, 37]])
the other product is:  tensor([[ 2,  3,  4,  5],
        [ 6, 11, 16, 21],
        [10, 19, 28, 37]])


In [12]:
v = torch.tensor([1, 2, 3])
v.shape

torch.Size([3])

In [13]:
u = torch.tensor([[1, 2, 3],
            [4, 5, 6]])
u.shape

torch.Size([2, 3])

In [14]:
w = u @ v
print(w)

tensor([14, 32])


In [15]:
w.shape

torch.Size([2])

In [16]:
matr_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
matr_2d.shape

torch.Size([2, 3])

In [17]:
matr_3d = torch.tensor([
    [[1, 2, 3, 4], 
    [-2, 5, 6, 9]], 
    
    [[5, 6, 7, 2], 
     [8, 9, 10, 4]],
    
    [[-3, 2, 2, 1], 
     [4, 6, 5, 9]]
])
matr_3d.shape

torch.Size([3, 2, 4])

In [18]:
rr = torch.arange(1, 16)
rr

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
rr.view(5, 3)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])

In [20]:
rr = rr.view(5, 3)
print(rr)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


In [21]:
# numpy to pytorch and vice-versa

import numpy as np

# numpy.ndarray --> torch.Tensor:
arr = np.array([[1, 0, 5]])
data = torch.tensor(arr)

print('this is torch.tensor', arr)


# torch.tensor --> numpy.ndarray:
new_arr = data.numpy()
print('this is numpy array', new_arr)

this is torch.tensor [[1 0 5]]
this is numpy array [[1 0 5]]


In [22]:
data = torch.arange(1, 36, dtype=torch.float32).reshape(5, 7)

# we can perform operations like "sum" over each column
print(data.sum(dim=0))

# or each row
print(data.sum(dim=1))

# we can do other operations as well
print(data.std(dim=1))

tensor([ 75.,  80.,  85.,  90.,  95., 100., 105.])
tensor([ 28.,  77., 126., 175., 224.])
tensor([2.1602, 2.1602, 2.1602, 2.1602, 2.1602])


In [23]:
data.sum()

tensor(630.)

In [24]:
data = torch.tensor([
    [1, 2.2, 9.6],
    [4, -7.2, 6.3]
])

data.shape

torch.Size([2, 3])

In [25]:
data.mean(dim=1)

tensor([4.2667, 1.0333])

In [26]:
data.mean(dim=0)

tensor([ 2.5000, -2.5000,  7.9500])

In [27]:
# Indexing

x = torch.tensor([
    [[1, 2], 
    [3, 4]], 
    
    [[5, 6], 
     [7, 8]],
    
    [[9, 10], 
     [11, 12]]
])
x.shape

torch.Size([3, 2, 2])

In [28]:
x[:, 0]

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])

In [29]:
x[0, :]

tensor([[1, 2],
        [3, 4]])

In [30]:
x[0]

tensor([[1, 2],
        [3, 4]])

In [31]:
# list indexing
x[[0, 2]]

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 9, 10],
         [11, 12]]])

In [32]:
x

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [33]:
x[:, 0, 0]

tensor([1, 5, 9])

In [34]:
x[:, :]

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [35]:
x[:, :, :]

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [36]:
x[0, 0, 0]

tensor(1)

In [37]:
x[0, 0, 0].item()

1

In [38]:
y = torch.tensor([
    [1, 2.2, 9.6],
    [4, -7.2, 6.3]
])

y.shape

torch.Size([2, 3])

In [39]:
# first column
y[:, 0]

tensor([1., 4.])

In [40]:
# first row
y[0, :]

tensor([1.0000, 2.2000, 9.6000])

In [41]:
# Autograd
# auto calculate gradients

x = torch.tensor([
    [[1, 2], 
    [3, 4]], 
    
    [[5, 6], 
     [7, 8]],
    
    [[9, 10], 
     [11, 12]]
], requires_grad = True, dtype=torch.float32)
x.shape

torch.Size([3, 2, 2])

In [42]:
y = 3 * (x ** 2)
z = y.sum()

z.backward()

pp.pprint(x.grad)

tensor([[[ 6., 12.],
         [18., 24.]],

        [[30., 36.],
         [42., 48.]],

        [[54., 60.],
         [66., 72.]]])


In [43]:
x = torch.tensor([2.], requires_grad=True)

pp.pprint(x.grad)

None


In [44]:
y = 3 * (x ** 2)

# backward propagation
y.backward()

pp.pprint(x.grad)

tensor([12.])


In [45]:
z = 3 * (x ** 2)

# backward propagation
z.backward()

pp.pprint(x.grad)

tensor([24.])


In [46]:
# Neural network module

In [47]:
import torch.nn as nn

In [48]:
input = torch.ones(2, 3, 4)
print(input)

# linear layer in pytorch takes 2 arguments, 1) input dimension, and 2) output dimension.
linear = nn.Linear(4, 2)
linear_output = linear(input)
sigmoid = nn.Sigmoid()
output = sigmoid(linear_output)
output

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


tensor([[[0.5104, 0.2008],
         [0.5104, 0.2008],
         [0.5104, 0.2008]],

        [[0.5104, 0.2008],
         [0.5104, 0.2008],
         [0.5104, 0.2008]]], grad_fn=<SigmoidBackward0>)

In [49]:
list(linear.parameters())

[Parameter containing:
 tensor([[ 0.0409,  0.2801, -0.0757,  0.2222],
         [-0.4167, -0.2807, -0.2774, -0.2993]], requires_grad=True),
 Parameter containing:
 tensor([-0.4257, -0.1069], requires_grad=True)]

In [50]:
# putting the layers together

block = nn.Sequential(
    nn.Linear(4, 2),
    nn.Sigmoid()
)

input = torch.ones(2, 3, 4)
output = block(input)
output

tensor([[[0.6370, 0.4955],
         [0.6370, 0.4955],
         [0.6370, 0.4955]],

        [[0.6370, 0.4955],
         [0.6370, 0.4955],
         [0.6370, 0.4955]]], grad_fn=<SigmoidBackward0>)

In [51]:
class MultiLayerPerceptron(nn.Module):

    def __init__(self, input_size, hidden_size):

        super(MultiLayerPerceptron, self).__init__()

        self.input_size = input_size
        self.hidden_size = hidden_size

        self.model = nn.Sequential(
            nn.Linear(self.input_size, self.hidden_size),
            nn.ReLU(),
            nn.Linear(self.hidden_size, self.input_size),
            nn.Sigmoid()
        )

    def forward(self, x):
        output = self.model(x)
        return output

In [52]:
input = torch.randn(2, 5)
model = MultiLayerPerceptron(5, 3)
model(input)

list(model.parameters())

[Parameter containing:
 tensor([[-0.0315, -0.0053,  0.2117, -0.4263, -0.4037],
         [-0.4428,  0.0306,  0.2557, -0.1449, -0.3250],
         [ 0.0814, -0.1601, -0.3944, -0.1025, -0.2492]], requires_grad=True),
 Parameter containing:
 tensor([ 0.4141, -0.0877, -0.4193], requires_grad=True),
 Parameter containing:
 tensor([[-0.0229, -0.3267, -0.3172],
         [-0.3144, -0.1666,  0.3103],
         [ 0.2963,  0.0281,  0.3693],
         [ 0.4080,  0.1957, -0.0006],
         [ 0.2512,  0.5393, -0.0342]], requires_grad=True),
 Parameter containing:
 tensor([-0.4146, -0.0068, -0.3808,  0.3416,  0.3478], requires_grad=True)]

In [58]:
y = torch.ones(10, 5)
x = y + torch.randn_like(y)
x

tensor([[ 2.6525,  1.5033,  1.0649,  1.5820,  1.5961],
        [ 0.9360,  1.0121,  0.3269,  0.3124,  0.1407],
        [ 1.4726,  0.3660,  2.7577,  1.5453,  0.1634],
        [ 1.2500,  1.5113, -0.2629,  0.7807, -0.5474],
        [-0.7894,  0.7371,  1.2991,  1.0853,  1.5647],
        [ 0.1380, -0.1107,  0.2996,  1.3256,  1.0410],
        [-0.3910,  0.9609,  1.3634,  0.5312,  1.3061],
        [ 1.6492, -0.2070,  0.9190,  1.6587,  1.2000],
        [ 2.0294,  0.6403, -0.2562,  0.6310, -1.1061],
        [ 1.4069,  1.0016, -0.2134, -0.7120,  2.3739]])

In [60]:
# optimization
import torch.optim as optim

model = MultiLayerPerceptron(5, 3)

adam = optim.Adam(model.parameters(), lr=1e-1)

# binary cross-entropy loss function
loss_function = nn.BCELoss()

y_pred = model(x)
loss_function(y_pred, y).item()

0.7474785447120667

In [63]:
# model training
n_epoch = 10

for epoch in range(n_epoch):
    
    adam.zero_grad()
    
    y_pred = model(x)
    
    loss = loss_function(y_pred, y)
    
    print(f"Epoch: {epoch}: training loss: {loss}")
    
    loss.backward()
    
    adam.step()

Epoch: 0: training loss: 0.7474785447120667
Epoch: 1: training loss: 0.601238489151001
Epoch: 2: training loss: 0.4604165554046631
Epoch: 3: training loss: 0.3263360559940338
Epoch: 4: training loss: 0.2135915756225586
Epoch: 5: training loss: 0.13015595078468323
Epoch: 6: training loss: 0.07496969401836395
Epoch: 7: training loss: 0.041624151170253754
Epoch: 8: training loss: 0.022727571427822113
Epoch: 9: training loss: 0.012415153905749321


In [64]:
y_pred = model(x)
y_pred

tensor([[1.0000, 1.0000, 0.9999, 1.0000, 1.0000],
        [0.9944, 0.9924, 0.9811, 0.9911, 0.9823],
        [1.0000, 0.9999, 0.9995, 0.9998, 0.9997],
        [0.9952, 0.9933, 0.9831, 0.9921, 0.9844],
        [0.9985, 0.9974, 0.9922, 0.9966, 0.9936],
        [0.9945, 0.9925, 0.9813, 0.9912, 0.9825],
        [0.9982, 0.9970, 0.9910, 0.9961, 0.9925],
        [0.9999, 0.9997, 0.9985, 0.9995, 0.9991],
        [0.9893, 0.9872, 0.9714, 0.9858, 0.9713],
        [0.9981, 0.9969, 0.9908, 0.9960, 0.9923]], grad_fn=<SigmoidBackward0>)